include(CheckIncludeFile)
include(CheckSymbolExists)
include(CheckTypeSize)

check_symbol_exists(atoll "stdlib.h" HAVE_ATOLL)
check_include_file(direct.h HAVE_DIRECT_H)
check_symbol_exists(gai_strerror "sys/types.h;sys/socket.h;netdb.h" HAVE_GAI_STRERROR)
check_symbol_exists(getaddrinfo "sys/types.h;sys/socket.h;netdb.h" HAVE_GETADDRINFO)
check_symbol_exists(getnameinfo "sys/types.h;sys/socket.h;netdb.h" HAVE_GETNAMEINFO)
check_include_file(iconv.h HAVE_ICONV_H)
check_symbol_exists(iconv_open "iconv.h" HAVE_ICONV_OPEN)
check_include_file(langinfo.h HAVE_LANGINFO_H)
check_include_file(libcharset.h HAVE_LIBCHARSET_H)
check_symbol_exists(locale_charset "libcharset.h" HAVE_LOCALE_CHARSET)
check_include_file(locale.h HAVE_LOCALE_H)
check_include_file(mbstring.h HAVE_MBSTRING_H)
check_include_file(net/if.h HAVE_NET_IF_H)
check_symbol_exists(nl_langinfo "langinfo.h" HAVE_NL_LANGINFO)
check_symbol_exists(setlocale "locale.h" HAVE_SETLOCALE)
check_symbol_exists(strcasecmp "strings.h" HAVE_STRCASECMP)
set(CMAKE_EXTRA_INCLUDE_FILES "sys/socket.h;netinet/in.h")
check_type_size("struct in6_addr" STRUCT_IN6_ADDR)
check_type_size("struct sockaddr_in6" STRUCT_SOCKADDR_IN6)
check_type_size("struct sockaddr_storage" STRUCT_SOCKADDR_STORAGE)
check_symbol_exists(_getdcwd "direct.h" HAVE__GETDCWD)
check_symbol_exists(_atoi64 "stdlib.h" HAVE__ATOI64)

configure_file(cmake/config.h.in config.h)
